# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file.

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [1]:
# Import pandas using the standard alias
import pandas as pd

In [12]:
# formula to convert to pd file and save with file name
# -pd.read_csv('File_name/csv_filename.csv') 
# -pd.read_excel('File_name/excel_filname.xlsx')

In [13]:
df =pd.read_csv('Data/Zipcode_Demos.csv') 
df.head()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Import the file and print the first 5 rows
df = pd.read_excel('Data/Zipcode_Demos.xlsx')
df.head

<bound method NDFrame.head of                                       0          Unnamed: 1    Unnamed: 2  \
0                    Average Statistics                 NaN           NaN
1                                   NaN                   0           NaN
2                     JURISDICTION NAME             10005.8           NaN
3                    COUNT PARTICIPANTS                 9.4           NaN
4                          COUNT FEMALE                 4.8           NaN
5                        PERCENT FEMALE               0.404           NaN
6                            COUNT MALE                 4.6           NaN
7                          PERCENT MALE               0.396           NaN
8                  COUNT GENDER UNKNOWN                   0           NaN
9                PERCENT GENDER UNKNOWN                   0           NaN
10                   COUNT GENDER TOTAL                 9.4           NaN
11                 PERCENT GENDER TOTAL                  80           NaN
12               COUNT PACIFIC ISLANDER                   0           NaN
13             PERCENT PACIFIC ISLANDER                   0           NaN
14                COUNT HISPANIC LATINO                   2           NaN
15              PERCENT HISPANIC LATINO               0.105           NaN
16                COUNT AMERICAN INDIAN                   0           NaN
17              PERCENT AMERICAN INDIAN                   0           NaN
18             COUNT ASIAN NON HISPANIC                 3.6           NaN
19           PERCENT ASIAN NON HISPANIC               0.437           NaN
20             COUNT WHITE NON HISPANIC                 0.8           NaN
21           PERCENT WHITE NON HISPANIC               0.036           NaN
22             COUNT BLACK NON HISPANIC                 2.6           NaN
23           PERCENT BLACK NON HISPANIC               0.181           NaN
24                COUNT OTHER ETHNICITY                 0.4           NaN
25              PERCENT OTHER ETHNICITY                0.04           NaN
26              COUNT ETHNICITY UNKNOWN                   0           NaN
27            PERCENT ETHNICITY UNKNOWN                   0           NaN
28                COUNT ETHNICITY TOTAL                 9.4           NaN
29              PERCENT ETHNICITY TOTAL                79.9           NaN
30       COUNT PERMANENT RESIDENT ALIEN                 0.5           NaN
31     PERCENT PERMANENT RESIDENT ALIEN               0.061           NaN
32                     COUNT US CITIZEN                 8.9           NaN
33                   PERCENT US CITIZEN               0.739           NaN
34           COUNT OTHER CITIZEN STATUS                   0           NaN
35         PERCENT OTHER CITIZEN STATUS                   0           NaN
36         COUNT CITIZEN STATUS UNKNOWN                   0           NaN
37       PERCENT CITIZEN STATUS UNKNOWN                   0           NaN
38           COUNT CITIZEN STATUS TOTAL                 9.4           NaN
39         PERCENT CITIZEN STATUS TOTAL                  80           NaN
40     COUNT RECEIVES PUBLIC ASSISTANCE                 2.3           NaN
41   PERCENT RECEIVES PUBLIC ASSISTANCE               0.151           NaN
42    COUNT NRECEIVES PUBLIC ASSISTANCE                 7.1           NaN
43  PERCENT NRECEIVES PUBLIC ASSISTANCE               0.649           NaN
44      COUNT PUBLIC ASSISTANCE UNKNOWN                   0           NaN
45    PERCENT PUBLIC ASSISTANCE UNKNOWN                   0           NaN
46        COUNT PUBLIC ASSISTANCE TOTAL                 9.4           NaN
47                    JURISDICTION NAME  COUNT PARTICIPANTS  COUNT FEMALE
48                                10001                  44            22
49                                10002                  35            19
50                                10003                   1             1
51                                10004                   0             0
52                                10005                   2             2
53                                10006                   6             2
54                                10007                   1             0
55                                10009                   2             0
56                                10010                   0             0
57                                10011                   3             2

        Unnamed: 3  Unnamed: 4    Unnamed: 5            Unnamed: 6  \
0              NaN         NaN           NaN                   NaN
1              NaN         NaN           NaN                   NaN
2              NaN         NaN           NaN                   NaN
3              NaN         NaN           NaN                   NaN
4              NaN         NaN           NaN                   NaN
5              NaN         NaN           NaN                   NaN
6              NaN         NaN           NaN                   NaN
7              NaN         NaN           NaN                   NaN
8              NaN         NaN           NaN                   NaN
9              NaN         NaN           NaN                   NaN
10             NaN         NaN           NaN                   NaN
11             NaN         NaN           NaN                   NaN
12             NaN         NaN           NaN                   NaN
13             NaN         NaN           NaN                   NaN
14             NaN         NaN           NaN                   NaN
15             NaN         NaN           NaN                   NaN
16             NaN         NaN           NaN                   NaN
17             NaN         NaN           NaN                   NaN
18             NaN         NaN           NaN                   NaN
19             NaN         NaN           NaN                   NaN
20             NaN         NaN           NaN                   NaN
21             NaN         NaN           NaN                   NaN
22             NaN         NaN           NaN                   NaN
23             NaN         NaN           NaN                   NaN
24             NaN         NaN           NaN                   NaN
25             NaN         NaN           NaN                   NaN
26             NaN         NaN           NaN                   NaN
27             NaN         NaN           NaN                   NaN
28             NaN         NaN           NaN                   NaN
29             NaN         NaN           NaN                   NaN
30             NaN         NaN           NaN                   NaN
31             NaN         NaN           NaN                   NaN
32             NaN         NaN           NaN                   NaN
33             NaN         NaN           NaN                   NaN
34             NaN         NaN           NaN                   NaN
35             NaN         NaN           NaN                   NaN
36             NaN         NaN           NaN                   NaN
37             NaN         NaN           NaN                   NaN
38             NaN         NaN           NaN                   NaN
39             NaN         NaN           NaN                   NaN
40             NaN         NaN           NaN                   NaN
41             NaN         NaN           NaN                   NaN
42             NaN         NaN           NaN                   NaN
43             NaN         NaN           NaN                   NaN
44             NaN         NaN           NaN                   NaN
45             NaN         NaN           NaN                   NaN
46             NaN         NaN           NaN                   NaN
47  PERCENT FEMALE  COUNT MALE  PERCENT MALE  COUNT GENDER UNKNOWN
48             0.5          22           0.5                     0
49            0.54          16          0.46                     0
50               1           0             0                     0
51               0           0             0                     0
52               1           0             0                     0
53            0.33           4          0.67                     0
54               0           1             1                     0
55               0           2             1                     0
56               0           0             0                     0
57            0.67           1          0.33                     0

                Unnamed: 7          Unnamed: 8            Unnamed: 9  ...  \
0                      NaN                 NaN                   NaN  ...
1                      NaN                 NaN                   NaN  ...
2                      NaN                 NaN                   NaN  ...
3                      NaN                 NaN                   NaN  ...
4                      NaN                 NaN                   NaN  ...
5                      NaN                 NaN                   NaN  ...
6                      NaN                 NaN                   NaN  ...
7                      NaN                 NaN                   NaN  ...
8                      NaN                 NaN                   NaN  ...
9                      NaN                 NaN                   NaN  ...
10                     NaN                 NaN                   NaN  ...
11                     NaN                 NaN                   NaN  ...
12                     NaN                 NaN                   NaN  ...
13                     NaN                 NaN                   NaN  ...
14                     NaN                 NaN                   NaN  ...
15                     NaN                 NaN                   NaN  ...
16                     NaN                 NaN                   NaN  ...
17                     NaN                 NaN                   NaN  ...
18                     NaN                 NaN                   NaN  ...
19                     NaN                 NaN                   NaN  ...
20                     NaN                 NaN                   NaN  ...
21                     NaN                 NaN                   NaN  ...
22                     NaN                 NaN                   NaN  ...
23                     NaN                 NaN                   NaN  ...
24                     NaN                 NaN                   NaN  ...
25                     NaN                 NaN                   NaN  ...
26                     NaN                 NaN                   NaN  ...
27                     NaN                 NaN                   NaN  ...
28                     NaN                 NaN                   NaN  ...
29                     NaN                 NaN                   NaN  ...
30                     NaN                 NaN                   NaN  ...
31                     NaN                 NaN                   NaN  ...
32                     NaN                 NaN                   NaN  ...
33                     NaN                 NaN                   NaN  ...
34                     NaN                 NaN                   NaN  ...
35                     NaN                 NaN                   NaN  ...
36                     NaN                 NaN                   NaN  ...
37                     NaN                 NaN                   NaN  ...
38                     NaN                 NaN                   NaN  ...
39                     NaN                 NaN                   NaN  ...
40                     NaN                 NaN                   NaN  ...
41                     NaN                 NaN                   NaN  ...
42                     NaN                 NaN                   NaN  ...
43                     NaN                 NaN                   NaN  ...
44                     NaN                 NaN                   NaN  ...
45                     NaN                 NaN                   NaN  ...
46                     NaN                 NaN                   NaN  ...
47  PERCENT GENDER UNKNOWN  COUNT GENDER TOTAL  PERCENT GENDER TOTAL  ...
48                       0                  44                   100  ...
49                       0                  35                   100  ...
50                       0                   1                   100  ...
51                       0                   0                     0  ...
52                       0                   2                   100  ...
53                       0                   6                   100  ...
54                       0                   1                   100  ...
55                       0                   2                   100  ...
56                       0                   0                     0  ...
57                       0                   3                   100  ...

                   Unnamed: 36                   Unnamed: 37  \
0                          NaN                           NaN
1                          NaN                           NaN
2                          NaN                           NaN
3                          NaN                           NaN
4                          NaN                           NaN
5                          NaN                           NaN
6                          NaN                           NaN
7                          NaN                           NaN
8                          NaN                           NaN
9                          NaN                           NaN
10                         NaN                           NaN
11                         NaN                           NaN
12                         NaN                           NaN
13                         NaN                           NaN
14                         NaN                           NaN
15                         NaN                           NaN
16                         NaN                           NaN
17                         NaN                           NaN
18                         NaN                           NaN
19                         NaN                           NaN
20                         NaN                           NaN
21                         NaN                           NaN
22                         NaN                           NaN
23                         NaN                           NaN
24                         NaN                           NaN
25                         NaN                           NaN
26                         NaN                           NaN
27                         NaN                           NaN
28                         NaN                           NaN
29                         NaN                           NaN
30                         NaN                           NaN
31                         NaN                           NaN
32                         NaN                           NaN
33                         NaN                           NaN
34                         NaN                           NaN
35                         NaN                           NaN
36                         NaN                           NaN
37                         NaN                           NaN
38                         NaN                           NaN
39                         NaN                           NaN
40                         NaN                           NaN
41                         NaN                           NaN
42                         NaN                           NaN
43                         NaN                           NaN
44                         NaN                           NaN
45                         NaN                           NaN
46                         NaN                           NaN
47  COUNT CITIZEN STATUS TOTAL  PERCENT CITIZEN STATUS TOTAL
48                          44                           100
49                          35                           100
50                           1                           100
51                           0                             0
52                           2                           100
53                           6                           100
54                           1                           100
55                           2                           100
56                           0                             0
57                           3                           100

                         Unnamed: 38                         Unnamed: 39  \
0                                NaN                                 NaN
1                                NaN                                 NaN
2                                NaN                                 NaN
3                                NaN                                 NaN
4                                NaN                                 NaN
5                                NaN                                 NaN
6                                NaN                                 NaN
7                                NaN                                 NaN
8                                NaN                                 NaN
9                                NaN                                 NaN
10                               NaN                                 NaN
11                               NaN                                 NaN
12                               NaN                                 NaN
13                               NaN                                 NaN
14                               NaN                                 NaN
15                               NaN                                 NaN
16                               NaN                                 NaN
17                               NaN                                 NaN
18                               NaN                                 NaN
19                               NaN                                 NaN
20                               NaN                                 NaN
21                               NaN                                 NaN
22                               NaN                                 NaN
23                               NaN                                 NaN
24                               NaN                                 NaN
25                               NaN                                 NaN
26                               NaN                                 NaN
27                               NaN                                 NaN
28                               NaN                                 NaN
29                               NaN                                 NaN
30                               NaN                                 NaN
31                               NaN                                 NaN
32                               NaN                                 NaN
33                               NaN                                 NaN
34                               NaN                                 NaN
35                               NaN                                 NaN
36                               NaN                                 NaN
37                               NaN                                 NaN
38                               NaN                                 NaN
39                               NaN                                 NaN
40                               NaN                                 NaN
41                               NaN                                 NaN
42                               NaN                                 NaN
43                               NaN                                 NaN
44                               NaN                                 NaN
45                               NaN                                 NaN
46                               NaN                                 NaN
47  COUNT RECEIVES PUBLIC ASSISTANCE  PERCENT RECEIVES PUBLIC ASSISTANCE
48                                20                                0.45

In [15]:
# Import the file and print the first 5 rows

In [16]:
# Print the last 5 rows of df
df.tail(5)

,0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
53,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
54,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
55,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
56,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100

In [21]:
# What is going on with this data set? Anything unusual?
df.info()
df.shape
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 46 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   0            57 non-null     object
 1   Unnamed: 1   57 non-null     object
 2   Unnamed: 2   11 non-null     object
 3   Unnamed: 3   11 non-null     object
 4   Unnamed: 4   11 non-null     object
 5   Unnamed: 5   11 non-null     object
 6   Unnamed: 6   11 non-null     object
 7   Unnamed: 7   11 non-null     object
 8   Unnamed: 8   11 non-null     object
 9   Unnamed: 9   11 non-null     object
 10  Unnamed: 10  11 non-null     object
 11  Unnamed: 11  11 non-null     object
 12  Unnamed: 12  11 non-null     object
 13  Unnamed: 13  11 non-null     object
 14  Unnamed: 14  11 non-null     object
 15  Unnamed: 15  11 non-null     object
 16  Unnamed: 16  11 non-null     object
 17  Unnamed: 17  11 non-null     object
 18  Unnamed: 18  11 non-null     object
 19  Unnamed: 19  11 non-null     object
 20  Unnamed: 20  11 non-null     object
 21  Unnamed: 21  11 non-null     object
 22  Unnamed: 22  11 non-null     object
 23  Unnamed: 23  11 non-null     object
 24  Unnamed: 24  11 non-null     object
 25  Unnamed: 25  11 non-null     object
 26  Unnamed: 26  11 non-null     object
 27  Unnamed: 27  11 non-null     object
 28  Unnamed: 28  11 non-null     object
 29  Unnamed: 29  11 non-null     object
 30  Unnamed: 30  11 non-null     object
 31  Unnamed: 31  11 non-null     object
 32  Unnamed: 32  11 non-null     object
 33  Unnamed: 33  11 non-null     object
 34  Unnamed: 34  11 non-null     object
 35  Unnamed: 35  11 non-null     object
 36  Unnamed: 36  11 non-null     object
 37  Unnamed: 37  11 non-null     object
 38  Unnamed: 38  11 non-null     object
 39  Unnamed: 39  11 non-null     object
 40  Unnamed: 40  11 non-null     object
 41  Unnamed: 41  11 non-null     object
 42  Unnamed: 42  11 non-null     object
 43  Unnamed: 43  11 non-null     object
 44  Unnamed: 44  11 non-null     object
 45  Unnamed: 45  11 non-null     object
dtypes: object(46)
memory usage: 21.0+ KB

,0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,Average Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,COUNT MALE,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PERCENT MALE,0.396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,COUNT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PERCENT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,COUNT GENDER TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PERCENT GENDER TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,COUNT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,PERCENT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,COUNT HISPANIC LATINO,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,PERCENT HISPANIC LATINO,0.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,COUNT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,PERCENT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,COUNT ASIAN NON HISPANIC,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PERCENT ASIAN NON HISPANIC,0.437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,COUNT WHITE NON HISPANIC,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,PERCENT WHITE NON HISPANIC,0.036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,COUNT BLACK NON HISPANIC,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,PERCENT BLACK NON HISPANIC,0.181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,COUNT OTHER ETHNICITY,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,PERCENT OTHER ETHNICITY,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,COUNT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,PERCENT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,COUNT ETHNICITY TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,PERCENT ETHNICITY TOTAL,79.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,COUNT PERMANENT RESIDENT ALIEN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,PERCENT PERMANENT RESIDENT ALIEN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,COUNT US CITIZEN,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,PERCENT US CITIZEN,0.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,COUNT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,PERCENT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,COUNT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,PERCENT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,COUNT CITIZEN STATUS TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,PERCENT CITIZEN STATUS TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
48,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
49,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
50,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
51,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
53,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
54,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
55,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
56,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100

In [24]:
import pandas as pd

# Load the dataset with pandas, using the updated argument 'on_bad_lines' to handle errors
df = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', on_bad_lines='skip')

# Step 1: Drop the "Unnamed" columns, which don't seem to contain any useful data
df_cleaned = df.loc[:, ~df.columns.str.contains('^Unnamed')]

# Step 2: Drop the first few rows that contain summary statistics or metadata
# For instance, if row 0 contains summary statistics, drop it
df_cleaned = df_cleaned.iloc[1:]

# Step 3: Reset index after dropping rows
df_cleaned.reset_index(drop=True, inplace=True)

# Step 4: Rename the columns (optional)
# If we know the correct column names, we can rename them. For now, we can leave them as is, or use the first row for headers if they were shifted
# Example of renaming columns, assuming the first row after cleanup is the actual header row
df_cleaned.columns = df_cleaned.iloc[0]
df_cleaned = df_cleaned[1:]

# Step 5: Handle missing values
# Optionally, fill NaN values with a placeholder or drop rows/columns with excessive NaNs
df_cleaned.fillna("Not Available", inplace=True)  # Or use df_cleaned.dropna(axis=0) to drop rows with NaN values

# Step 6: Inspect the cleaned dataset
print(df_cleaned.head())

# Save the cleaned dataset to a new CSV file
df_cleaned.to_csv('Data/Yelp_Reviews_Cleaned.csv', index=False)

0  jtQARsP6P-LbkyjbO1qNGg  1  2014-10-23  1  LZp4UX5zK3e-c5ZGSeo3kA  1  \
1  Ums3gaP2qM3W1XcA5r6SsQ  0  2014-09-05  0  jsDu6QEJHbwP2Blom1PLCA  5
2  vgfcTvK81oD4r50NMjU2Ag  0  2011-02-25  0  pfavA0hr3nyqO61oupj-lA  1
3  yFumR3CWzpfvTH2FCthvVw  0  2016-06-15  0  STiFMww2z31siPY7BWNC2g  5
4  UBv8heCQR0RPnUQG0zkXIQ  0  2016-09-23  0  HkYqGb0Gplmmk-xlHTRBoA  1
5  hdgYnadxg0GANhWOJabr2g  0  2014-08-23  0  RgqWdZA4xR023iP3T6jVfA  5

0 Terrible. Dry corn bread. Rib tips were all fat and mushy and had no flavor. If you want bbq in this neighborhood go to john mulls roadkill grill. Trust me.  \
1  Delicious healthy food. The steak is amazing. ...
2  This place sucks. The customer service is horr...
3  I have been an Emerald Club member for a numbe...
4  The score should be negative. Its HORRIBLE. Th...
5  I went there twice and I am pretty happy with ...

0  3  msQe1u7Z_XuqjGoqhB0J5g
1  0  msQe1u7Z_XuqjGoqhB0J5g
2  2  msQe1u7Z_XuqjGoqhB0J5g
3  0  TlvV-xJhmh7LCwJYXkV-cg
4  0  NhOc64RsrTT1Dls50yYW8g
5  0  NhOc64RsrTT1Dls50yYW8g

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_Corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [20]:
import pandas as pd
try:
    
    df = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', error_bad_lines=False, warn_bad_lines=True)
    print(df.head())

except Exception as e:
    print(f"Error occurred: {e}")

Error occurred: read_csv() got an unexpected keyword argument 'error_bad_lines'

## Summary

Congratulations, you now practiced your Pandas-importing skills.